apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    component: cart
    project: roboshop
    tier: app
spec:
  selector:
    component: cart
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    ports: 8080
    targetPort: 8080